### ISSUE TITLE
some fine print / descriptions not displaying

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#550] opened 2024-09-16 21:37 UTC
https://beta.metaculus.com/questions/1/will-advanced-ligo-announce-discovery-of-gravitational-waves-by-jan-31-2016/
description / fine print not displaying (link issue?)
Possibly only for old questions from before fields were separated

**Comment by SylvainChevalier** [comment] 2024-10-09 09:43
Duplicate of #714

**Closed by SylvainChevalier** 2024-10-09 09:43 UTC
Labels: Bug Report, Medium Priority
