### ISSUE TITLE
Error when creating question with min date > max date

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#742] opened 2024-10-02 13:57 UTC
> I created a question with a min date > max date and it went through and I initially got an "Error. Try again" screen and now all I see is "Application error: a client-side exception has occurred (see the browser console for more information)."
> Console says `RangeError: Invalid time value  and Error: Minified React error #310; visit https://react.dev/errors/310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`  Minified React error #310 is `Rendered more hooks than during the previous render.` according to the link.

Reported by Nikitas

**Comment by lsabor** [comment] 2024-11-09 04:51
This shouldn't happen any more.
closing as complete

**Closed by lsabor** 2024-11-09 04:51 UTC
Labels: Bug Report, Medium Priority

**Comment by PatMyron** [comment] 2024-11-13 21:37
Still experiencing `RangeError: Invalid time value` when trying to create questions here:
https://www.metaculus.com/questions/create/group/?subtype=date

**Comment by hickman-santini** [comment] 2024-11-15 21:13
@PatMyron can you provide more detail? I can't reproduce; it just won't let me create a question when min > max date:

![image](https://github.com/user-attachments/assets/d684fc51-12bb-4dff-8b8c-4068c187b8cd)

**Comment by PatMyron** [comment] 2024-11-18 16:22
> won't let me create a question when min > max

Maybe individual min/max datetimes rather than just their relations? If both min/max datetimes are touched, and one's briefly invalid, it crashes:
`(Reproduction: change AM/PM on min or max, then change the month on the other to 11)`

Unintuitive to remember to not input leading zeroes and edit the day before the month because ~half the months don't have the default (31st)

Happening consistently on Chrome on Mac. Better luck with how `<input type="datetime-local">` works on mobile

https://www.metaculus.com/questions/create/question/?type=date defaults seem better than 
https://www.metaculus.com/questions/create/group/?subtype=date defaulting min and max to the [epoch](https://en.wikipedia.org/wiki/Epoch_(computing))
