### ISSUE TITLE
User reports issue with private comments

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1517] opened 2024-11-25 20:59 UTC
>I just posted a private comment on a question, and then immediately the page showed me, instead of my comment, some other comment, by another user. I then clicked over to public comments and back to private comments, and then it showed my comment (and not the other comment). I didn't make a note of what the other comment said or who it was by, but it was not at the top of the public comments on that page. I am particularly concerned that I may have been shown someone else's private comment.

https://www.metaculus.com/notebooks/28734/#comment-230784

**Comment by hickman-santini** [comment] 2024-11-25 22:33
@hlbmtc can you investigate this... It was user `darkives`

**Comment by ryooan** [comment] 2024-11-26 21:54
Update: https://www.metaculus.com/notebooks/28734/a-massive-rewrite-a-slate-of-improvements-and-going-open-source/#comment-231521

> This keeps happening, by the way. I just posted another private comment and was instead shown [this comment by RuslanBes](https://www.metaculus.com/questions/3820/#comment-231517) instead. (My private comment was not posted in that question.)

**Comment by nangchrys** [comment] 2024-11-27 01:08
Happened to me too on [this question](https://www.metaculus.com/questions/30295/will-bluesky-reach-30-million-users-before-1-january-2025/):
![image](https://github.com/user-attachments/assets/d6716893-d938-4820-9cb6-5b71e0744daa)

No idea where this comments is supposed to be from, but [here](https://www.metaculus.com/questions/30295/will-bluesky-reach-30-million-users-before-1-january-2025/#comment-232146)'s the link that I got from clicking Copy Link.

**Comment by joe-segal** [comment] 2024-11-27 04:40
I'm participating in the AI Bot Forecasting Contest and I've been getting a different issue with private comments recently, when using the API through https://www.metaculus.com/api/comments/.  Not sure if it could be a related issue.

On random questions here and there I will get an unexpected sorting of my comments returned.  Usually the list of comments will come back in chronological order as expected, but on certain questions here and there, and more so recently, the comments will be in some other order, so when I try to retrieve the most recent comment, it will return an earlier comment instead.  I figured out to add an additional "sort" element to the query string, which seems to fix it for me for now, but I still wanted to report the unexpected behavior, in case it could have wider repercussions.

Some recent questions this happens for me on are:
https://www.metaculus.com/questions/30494/will-the-temperature-in-san-francisco-ca-ever-go-below-40-degrees-f-in-the-entire-month-of-december-2024/
https://www.metaculus.com/questions/30491/on-december-31-2024-will-exactly-4-us-states-have-waymos-rider-only-ride-hailing-service-available-to-the-general-public/
https://www.metaculus.com/questions/30460/will-the-year-over-year-increase-in-prices-of-homes-in-dallas-tx-in-november-2024-be-greater-than-or-equal-to-00-according-to-zillow/
https://www.metaculus.com/questions/30459/will-the-year-over-year-increase-in-prices-of-homes-in-hartford-ct-in-november-2024-be-greater-than-or-equal-to-70-according-to-zillow/

I'm not sure what the focus_comment_id is, if this has anything to do with it.  I would be calling the API with a full URL like https://www.metaculus.com/api/comments/?post=30494&is_private=True and just added &sort=created_at (or &sort=id) which fixes it.  My bot account name is "histerio".

**Comment by hlbmtc** [comment] 2024-12-06 18:00
The problem was due to a small bug in the comment rendering process: after a comment was created, the frontend was not rendering the newly created one. Instead, it fetched the last comment from the post comments feed, which missed the `is_private=true` flag. As a result, the last public comment was rendered instead of the private comment the user had just created.

No private comments were exposed.

**Comment by hlbmtc** [comment] 2024-12-06 18:17
> Usually the list of comments will come back in chronological order as expected, but on certain questions here and there, and more so recently, the comments will be in some other order, so when I try to retrieve the most recent comment, it will return an earlier comment instead

Hmm, I think it might be because our backend paginates and sorts over 'root' comments only. The response contains a mix of root comments and their child comments. Child comments don't follow the requested sorting and are returned in full to build the thread without extra inner pagination.

> I'm not sure what the focus_comment_id

`focus_comment_id` is a parameter that tells the backend to bring a specific comment to the top, no matter the page, filters, or sorting settings. We added this to make it easy to jump to a specific comment using its link (e.g., `/28734/#comment-233535`), even if it's buried deep in the thread.

**Comment by SylvainChevalier** [comment] 2024-12-16 15:17
lgtm

**Closed by SylvainChevalier** 2024-12-16 15:17 UTC
Labels: Bug Report, Awaiting QA, Medium Priority
