### ISSUE TITLE
"An error has occurred when rendering the feed card..."

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#376] opened 2024-09-03 14:27 UTC
## Current behavior
`s.aggregations is undefined` - appears here and at least once more, three cards later
![image](https://github.com/user-attachments/assets/e1731d49-e243-4b40-9cd6-1592f27a6e02)

Reported by @Tommetaculus

**Comment by SylvainChevalier** [comment] 2024-11-07 15:52
Should have been fixed by recent performance improvements.

**Closed by SylvainChevalier** 2024-11-07 15:52 UTC
Labels: Bug Report

**Comment by Tommetaculus** [comment] 2024-11-07 17:08
Confirmed! It works for me now.
