### ISSUE TITLE
Change 'customise' (British spelling) to 'customize' (American) (low priority)

### ISSUE THREAD

**Issue by christianMet** [Metaculus/metaculus#1748] opened 2024-12-17 18:28 UTC
on Slack here: https://metaculus.slack.com/archives/C01Q9AQBVHB/p1734460031734669

Appears in the 'following' question interface

**Comment by SylvainChevalier** [comment] 2024-12-18 09:13
Duplicate of #425.

**Closed by SylvainChevalier** 2024-12-18 09:13 UTC
