### ISSUE TITLE
Possible scoring issue - sign inverted?

### ISSUE THREAD

**Issue by draaglom** [Metaculus/metaculus#1161] opened 2024-10-28 23:35 UTC
## Current behavior

https://www.metaculus.com/questions/28855/will-erik-ten-hag-be-fired-before-2025/

<img width="774" alt="image" src="https://github.com/user-attachments/assets/f236305d-e484-44c0-951f-f2e421ceb2fb">

On this question my forecast was < 50% and less than the community median the entire time, the question resolved **yes**, and yet I somehow have a positive baseline and peer score. This is surprising.

## Expected/desired behavior

- I'm sure I should not have a positive baseline score
- I'm pretty sure I should not have a positive peer score

Is the sign inverted?

**Comment by lsabor** [comment] 2024-10-29 14:13
That does look very strange. I forecasted 48% though and got a mildly negative baseline score.
If the moderator accidentally resolved to "No" mistakenly and then re-resolved to "Yes", there is a chance that this data is old. I'll check the database directly.

**Comment by lsabor** [comment] 2024-10-29 16:13
Through discussion, I found out that this question was initially accidentally resolved to a later date (Nov 11 was set as the "time resolution was known"). Then it was re-resolved to the correct resolution time (~oct 26). I think that the scores reflected the initial erroneous resolution, and for some reason the re-resolve didn't take properly.

I haven't yet gotten confirmation of this, but I'm wondering if the issue was that the re-resolution was in too close proximity to the initial resolution. Even if the code has no bugs, a race condition could have arose where the initial resolution took so long that it actually finished after the re-resolution, meaning that it would have overwritten all the scores.

I'll see if I can reproduce this locally while being patient for the resolution tasks to complete.

**Comment by nicobaga** [comment] 2024-10-30 13:43
@lsabor 

Potentially a very similar issue. 

The question linked below was resolved. It says I got only 6% coverage though I forecasted as soon as the question was available.

> Just resolved to yes. You made predictions, covering 6.0% of the question lifetime.

[Will any more United Kingdom MPs be suspended from their party, resign, or change allegiance before 2025?](https://www.metaculus.com/questions/28854/uk-mp-defection-suspension-or-resignation-before-2025/)

> What is the coverage?
The Coverage measures for what proportion of a question's lifetime you had a prediction standing.
If you make your first prediction right when the question opens, your coverage will be 100%. If you make your first prediction one second before the question closes, your coverage will be very close to 0%.
The Coverage is used in tournaments, to incentivize early predictions.


![metaculus_bug](https://github.com/user-attachments/assets/ec192a56-700c-4622-944e-b24be0cc8727)

**Comment by lsabor** [comment] 2024-10-30 14:18
"There were two reresolutions, one a few hours after the initial one and a second about an hour later." regarding the original question

**Comment by lsabor** [comment] 2024-10-30 14:24
@nicobaga That coverage is correct. In order for our scoring rules to be proper, we need to scale them by their coverage as calculated against the time the question is *scheduled to be open*. Since this question is set to close at the new year 2025, and it was only open for ~2 days, your prediction in fact only covered 6% of the question's lifetime.

We should improve the coverage documentation and illustrate with an example, though.

**Comment by lsabor** [comment] 2024-10-30 14:27
It's also worth noting that your "My Weighted Coverage" as shown in the drop down: "Additional Scores" should show a number much closer to 100%.

**Comment by nicobaga** [comment] 2024-10-30 15:27
@lsabor 

On second thoughts, it is not very clear. 

Is "_coverage_" affecting my score on the question and/or on the tournament as a whole?

**Comment by draaglom** [comment] 2024-10-30 20:10
@nicobaga the tl;dr is yes, an early resolving question brings your score closer to 0 (whether it was positive or negative). see https://www.metaculus.com/help/scores-faq/#score-truncation for more info and examples if you didn't already

**Comment by lsabor** [comment] 2024-10-30 23:30
@nicobaga @draaglom Sort of yes, but I prefer to conceptualize it that an early resolution doesn't bring your score closer to zero, instead it just stops you from accumulating more score.
Let's say you have a forecast that earns a score of 100, then for every 1% of the question's lifetime (open time until scheduled close time), you accrue 1 point. 
Imagine that a question asks "will X happen before DATE?". You immediately forecast, but the resolution becomes publicly known to be "yes" halfway to DATE. Any rational forecaster would then change their forecast to maximal probability "yes", and thus all forecasters would forecast the same value and everyone's peer score would necessarily be 0 for the remainder. There is no difference between this scenario (where you just start accruing a score of 0 after the resolution becomes known) and the one where coverage is truncated to the question's close time, at least in terms of score accumulation.

For peer scoring tournaments, your "coverage" is thus already effectively incorporated in your individual question scores. If you have nothing but predictions that score 100 in terms of peer score, for each question you would get `100*the coverage of the question`, and your tournament score would be the sum over those questions. Your take would be the square of that value.

For legacy "relative" scoring tournaments, your relative score is calculated with "weighted coverage" in place of coverage. So if the question resolved 99% early but you accrued a score of 100 for that 1% it was open, your relative score would still be 100. Your tournament take would then be your "average weighted coverage" `c` and "sum of relative scores" `s` put into the equation `c * e^s`.

Global peer leaderboards are close to peer scoring tournaments, except that it's the sum of your peer scores divided by the sum of your coverages, giving a coverage-weighted average of your peer scores.

Hope this helps a little.

**Comment by lsabor** [comment] 2024-11-04 22:49
After much prodding in a local instance of the codebase, I am unable to reproduce the anomalous results, specifically, but was able to get anomalous behavior by leaning on race conditions.
Since then there were a few bugs covering opening / closing times, so it may have been fixed by that. Otherwise, it's possible that the information wasn't accurate and there was in fact a race condition.
I'm going to make another ticket just to get rid of the race condition, closing this one.

**Closed by lsabor** 2024-11-04 22:49 UTC
Labels: High Priority, Technical
