### ISSUE TITLE
Personal predictions in the graph are not correct

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1152] opened 2024-10-26 17:41 UTC
[This question](https://www.metaculus.com/questions/26278/flu-us-vaccine-coverage-2024-25/)
![image](https://github.com/user-attachments/assets/ed856100-46ec-4fe2-a724-40c07c3b0149)

The numbers in the prediction maker don't correspond at all with the graph.

They also don't show up when I'm mouseovering the graph:
![image](https://github.com/user-attachments/assets/dff1b564-a704-44f5-810c-f45bd8aadc4c)

**Comment by hickman-santini** [comment] 2024-10-28 11:42
Closing as dupe of #1060

**Closed by hickman-santini** 2024-10-28 11:42 UTC
