### ISSUE TITLE
Mobile comment issue

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1739] opened 2024-12-17 10:47 UTC
I have been unable to send a comment via my phone for several days. When I hit reply, it multiplies the name of the user I reply to and stops me from commenting. There are a few other weird behaviours documented in the video.

I have a Z Fold 5, Chrome, Android 14 I think (happens in full or slab mode)

https://github.com/user-attachments/assets/e8a9508b-d366-4812-be04-04e481379503

**Comment by SylvainChevalier** [comment] 2024-12-17 12:27
I cant reproduce the locking, but I can reproduce "typing anything adds copies of the @ed username". Only on Chrome Android.

**Comment by ncarazon** [comment] 2024-12-17 13:02
@SylvainChevalier I wonder how you reproduced the "typing anything adds copies of the @ed username" issue. According to the original screencast, extra mention is added by MicrosoftSwiftkey (pressing space automatically adds whatever is suggested by the keyboard). So this is not a duplicated mention, created by the editor. Was it the same case for you? Could you share a screencast?

**Comment by ncarazon** [comment] 2024-12-17 16:20
I've tried to do some debugging in looks like this is a known issue with Android virtual keyboard in rich text editors: https://issues.chromium.org/issues/41254240 and it's not directly related to our editor implementation.

I applied a workaround that seem to resolve it, but in order to do a proper solution we would need to wait until it is fixed on Google Chrome.

**Comment by exmateriae** [comment] 2024-12-18 16:32
I still have parts of the issue : the doubling of the @ at the beginning still happens and even though I seem to be able to type, the bow is acting like it's searching for a username

**Comment by ncarazon** [comment] 2024-12-18 16:35
@exmateriae a fix wasn't deployed yet

**Comment by ncarazon** [comment] 2024-12-19 09:21
Ready for testing on prod

**Comment by SylvainChevalier** [comment] 2024-12-19 13:17
Much better, thanks @ncarazon.

**Closed by SylvainChevalier** 2024-12-19 13:17 UTC
Labels: Bug Report, Awaiting QA, High Priority
