### ISSUE TITLE
Community landing page doesn't show Community Name in Header

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1628] opened 2024-12-09 14:48 UTC
Here is the Community search page:
![image](https://github.com/user-attachments/assets/7c9ad9b0-50dc-4a73-a4ea-d24c72d30937)

Here is one of the questions:
![image](https://github.com/user-attachments/assets/dd870853-10f2-496a-a336-4bbb55f495f1)

**Comment by ncarazon** [comment] 2024-12-10 14:45
@lsabor this is expected. This behavior is intentional. The community name is hidden in the header by design when it is already displayed in the heading section. As you scroll down, it will reappear.


https://github.com/user-attachments/assets/a46bcd8e-f27d-42e7-a3fb-8cef1b676c7e

**Comment by ncarazon** [comment] 2024-12-16 11:39
@SylvainChevalier @aseckin could you please check if we should actually fix this?

**Comment by SylvainChevalier** [comment] 2024-12-16 13:28
seems fine to me, closing.

**Closed by SylvainChevalier** 2024-12-16 13:28 UTC
Labels: Simple, Bug Report, High Priority
