### ISSUE TITLE
Significant change notifications are wrong

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1085] opened 2024-10-21 14:47 UTC
Significant change emails are sent when they shouldn't be:
![image](https://github.com/user-attachments/assets/28cbb3fd-19b2-4dec-8eed-b3ade258f591)
but hopefuly this is a result of the migration and will be fixed on its own.

More worryingly, it seems implausible that all options [here](https://www.metaculus.com/questions/21095/will-the-following-years-be-the-warmest-year-on-record/) moved by the exact same amount
![image](https://github.com/user-attachments/assets/8445e643-9aa1-4426-bbb5-7ad83a11fb88)
also the order of the options is random, the Community Now column has wrong values (unless all of them changed in different directions since I got the email), there is no "since day X" text for group questions (and maybe multiple choice ones?), and the direction of the movement is not mentioned.

**Comment by SylvainChevalier** [comment] 2024-10-22 08:04
Duplicate of #929

**Closed** 2024-10-22 12:25 UTC
Labels: High Priority
