### ISSUE TITLE
Score and medal discrepancies

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#495] opened 2024-09-11 21:15 UTC
> In the Q3 2023 tournament, which should be stable by now, I found differences between the [standard platform ](https://www.metaculus.com/tournament/quarterly-cup-2023q3/)and the [beta](https://beta.metaculus.com/tournament/quarterly-cup-2023q3/). Some of the individual scores, such as mine, differ between the two versions. Also, the original version only gives 42 medals, while the beta shows 43 winners. Relatedly, checking the [Real-Time Pandemic Decision Making tournament](https://beta.metaculus.com/tournament/realtimepandemic/), it seems that some (such as myself) have gone up in medal ranking (such as from copper to silver). This seems likely to be due to a change in how rounding is handled, but I don't know if it is intentional.

Reported by Sergio

**Comment by lsabor** [comment] 2024-09-12 15:11
Great catch to Sergio!
It seems like maybe conditional question resolutions weren't successfully migrated.

**Comment by lsabor** [comment] 2024-09-12 17:56
Fixed the scoring descrepency - the ArchivedScore migration missed conditional questions so they weren't counted in legacy scored tournaments. Results will take effect after next migration (or if I just call it manually)

The medals earning difference is caused by a known issue where moderators aren't disqualified in the rewrite so they are included in the total count of competitors - so the number of winners (the top 5%) is dependent on this and can effect the results on the margin. This error is strictly good for users, but will eventually be fixed. I'll make that into a separate medium priority task and close this one.

**Closed by lsabor** 2024-09-12 17:56 UTC
Labels: Approved, Bug Report, High Priority

**Comment by hickman-santini** [comment] 2024-09-13 19:04
> The medals earning difference is caused by a known issue where moderators aren't disqualified in the rewrite so they are included in the total count of competitors - so the number of winners (the top 5%) is dependent on this and can effect the results on the margin. This error is strictly good for users, but will eventually be fixed. I'll make that into a separate medium priority task and close this one.

Confused by this - moderators should be disqualified. They will eventually be disqualified. It seems like disqualifying mods should be good for users (not the error). What am I missing @lsabor?

**Comment by hickman-santini** [comment] 2024-09-13 19:06
> The medals earning difference is caused by a known issue where moderators aren't disqualified in the rewrite so they are included in the total count of competitors - so the number of winners (the top 5%) is dependent on this and can effect the results on the margin. This error is strictly good for users, but will eventually be fixed. I'll make that into a separate medium priority task and close this one.

Confused by this and I don't see the new issue yet so I'll ask here: Do you mean fixing the error will be good for (non-mode) users i.e. move them up in the ranks by disqualifying mods?
