### ISSUE TITLE
Min/max date inputs error badly if you input an invalid date

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1448] opened 2024-11-19 14:25 UTC
## Current behavior
Following up on https://github.com/Metaculus/metaculus/issues/742#issuecomment-2483516922

> If both min/max datetimes are touched, and one's briefly invalid, it crashes:
(Reproduction: flip AM/PM on min or max, then change the other month to 11)

(You get an "Error: Try again" page and lose your work)

> Unintuitive to remember to not input leading zeroes and edit days before months because ~half the months don't have the default (31st)

> Happens consistently on Chrome on Mac. Better luck with how `<input type="datetime-local">` works on mobile

While we're at it:

> https://www.metaculus.com/questions/create/question/?type=date defaults seem better than
https://www.metaculus.com/questions/create/group/?subtype=date defaulting min and max to the [epoch](https://en.wikipedia.org/wiki/Epoch_(computing))

@ncarazon can you just remove the epoch defaults from group date question creation?
![image](https://github.com/user-attachments/assets/4534b9b6-9334-4856-bec6-ff9ce6f3e702)

**Comment by SylvainChevalier** [comment] 2024-11-19 14:36
Duplicate of #1371, copying here for consolidation:

If I press 0 here
![image](https://github.com/user-attachments/assets/0e72ed50-bed0-4402-bb6a-5e7ba9f8a1c2)
I get this
![image](https://github.com/user-attachments/assets/d6e2a9ea-fe74-414b-8b70-9101c291d46b)

I assume because the creator is trying to make a graph with an invalid date. I know I don't need to press 0 for anything (I can just do 1 for 01), but if I forget and press it I lose all of my progress on the question.

tbc, to reproduce:

- create date qestion
- enter valid min and max dates
- the pdf graph appears
- enter 0 in either min or max date
- error

**Comment by ncarazon** [comment] 2024-11-26 09:17
Ready for testing on dev

**Comment by SylvainChevalier** [comment] 2024-11-26 12:59
Doesn't crash anymore, but now when I enter an invalid date it doesn't show an error until I try to submit.

![image](https://github.com/user-attachments/assets/e4c5d09a-8f12-4882-aa4e-50cd51e2957b)

Steps:
1. create date question
2. enter <i>in</i>valid min or max date
3. get error message (as expected)
4. change to valid min and max dates
5. error message disappears (as expected)
6. change to <i>in</i>valid min or max date again
7. no error message (there should be one)

**Comment by ncarazon** [comment] 2024-12-03 09:26
Ready for testing on dev

**Comment by SylvainChevalier** [comment] 2024-12-05 13:43
lgtm.

**Closed** 2024-12-05 15:33 UTC
Labels: Bug Report, Awaiting QA, Medium Priority
