### ISSUE TITLE
Can't edit this open question

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#951] opened 2024-10-10 21:53 UTC
I can't edit this open question to clarify it, I can get to the edit interface but when I click the "edit question" button to submit the edit it does nothing. <https://www.metaculus.com/questions/6113/autonomous-flying-cars-when/>

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1728597177624539)

**Comment by hlbmtc** [comment] 2024-10-11 14:14
@lsabor Has fixed it

**Comment by ryooan** [comment] 2024-10-18 14:41
@hlbmtc @lsabor can you please reopen this one, I still can't edit the question I linked above.

**Comment by ryooan** [comment] 2024-10-18 20:49
Here's another pending one myself and John are both unable to edit, we can access the edit menu but when we click the "edit question" button to submit it it does nothing. https://www.metaculus.com/questions/28942/number-of-weeks-with-high-ili-activity-2024-2025-flu-season/

**Comment by lsabor** [comment] 2024-10-18 22:51
I'm not having any trouble editing it. So I'm not sure what's going on there. Maybe a permissions issue?

**Comment by ryooan** [comment] 2024-10-18 22:55
It looks like John and I both have admin permissions in that project.

**Comment by lsabor** [comment] 2024-10-19 04:03
After some troubleshooting live with Ryan we discovered that the scaling values (range_min, range_max, and zero_point) don't get populated until interacted with (a problem of not pre-setting the local variables at page load). This doesn't work for questions that already have forecasts on them since the scaling becomes fixed at that point and can't be interacted with any more.

Questions can still be edited in the admin panel directly, but this ticket must remain open until the issue is fixed.

**Comment by SylvainChevalier** [comment] 2024-10-22 12:43
I assume this is an FE problem, should this be assigned to @ncarazon?

**Comment by ryooan** [comment] 2024-10-22 12:51
One thing to note too, the open upper and lower bound checkboxes are currently reversed, they activate the opposite. Not sure if tracked elsewhere but would be good to fix with this I'd think.

**Comment by ncarazon** [comment] 2024-10-23 13:03
Ready for testing on dev

**Comment by hickman-santini** [comment] 2024-10-23 19:27
Adding fine print in "Edit" on [this](https://dev.metaculus.com/questions/1088/date-of-birth-of-last-human-being/) open question didn't make a difference. Otherwise looks good, but @ncarazon can you fix this?

**Comment by ncarazon** [comment] 2024-10-24 08:18
@hickman-santini could you provide more context about this one? I tried to edit fine print and it seems to work

**Comment by lsabor** [comment] 2024-10-24 22:15
I was also able to edit the fine print successfully. I think this is ready to be closed

**Comment by hickman-santini** [comment] 2024-10-25 13:24
Huh. My mistake! Closing.

**Comment by nangchrys** [comment] 2024-11-11 18:27
> One thing to note too, the open upper and lower bound checkboxes are currently reversed, they activate the opposite. Not sure if tracked elsewhere but would be good to fix with this I'd think.

This is still the case for group continuous questions.

**Comment by ncarazon** [comment] 2024-11-12 11:32
Fix for https://github.com/Metaculus/metaculus/issues/951#issuecomment-2468790214 is ready for testing on prod

**Comment by SylvainChevalier** [comment] 2024-11-12 14:39
lgtm!

**Closed by SylvainChevalier** 2024-11-12 14:39 UTC
Labels: Bug Report, Awaiting QA, High Priority
