### ISSUE TITLE
Consider enabling Twitter/ X posts in comments

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1587] opened 2024-12-05 13:44 UTC
On old Metaculus Twitter links automatically showed up as embeds. I thought this was handy for people to share quick news updates. Curious if others would like to see that brought back. Potentially could consider expanding it to show previews of news links as well, and the option to collapse a preview and not show it like you can on slack?

**Comment by SylvainChevalier** [comment] 2024-12-10 15:35
Note: twitter has a piece of code we can use.

**Comment by ncarazon** [comment] 2024-12-20 11:16
Duplicate of https://github.com/Metaculus/metaculus/issues/917

**Closed by ncarazon** 2024-12-20 11:16 UTC
Labels: Feature Request, Medium Priority
