### ISSUE TITLE
markdown issue

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#1142] opened 2024-10-25 17:10 UTC
[@darkives](/accounts/profile/103907) Yeah, there is a bug in there.
If you switch to the Markdown version, you get finer control, but there seems to be a bug where if you put
\> Paragraph 1
\>
\> Paragraph 2
It appears as

> Paragraph 1Paragraph 2

Rather than

> Paragraph 1
> .
> Paragraph 2

(but without the period)

I'll make a ticket for it.

**Comment by lsabor** [comment] 2024-10-25 17:10
From: https://www.metaculus.com/notebooks/28734/a-massive-rewrite-a-slate-of-improvements-and-going-open-source/#comment-206595

**Comment by hickman-santini** [comment] 2024-10-28 11:48
Closing as dupe of https://github.com/Metaculus/metaculus/issues/1104

**Closed by hickman-santini** 2024-10-28 11:48 UTC
