### ISSUE TITLE
Circles for 'your predictions' on multi-choice don't always correspond to the colors of the options

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#415] opened 2024-09-04 14:53 UTC
## Current behavior
E.g. draaglom's predictions here (yellow circles should be red):
![image](https://github.com/user-attachments/assets/c66b06eb-d1e3-442e-afa6-45ed22639ac3)

**Comment by ncarazon** [comment] 2024-09-06 08:33
This is a duplicate of https://github.com/Metaculus/metaculus/issues/385 and should be fixed on dev. 

@George3d6 the fix was merged on September 4th. Have we updated the beta since then?

**Closed** 2024-09-06 12:52 UTC
Labels: Bug Report, High Priority

**Comment by hickman-santini** [comment] 2024-09-06 12:54
Confirming this looks to be fixed.
