### ISSUE TITLE
Big problem with the filter tab 

### ISSUE THREAD

**Issue by exmateriae** [Metaculus/metaculus#1350] opened 2024-11-10 12:59 UTC
Sorry for the terrible naming but I don't know how to call this bug.

Often when I open the "Filter" tab it appears fine but when you hover your mouse over anything it's like the "background" (the rectangle with the forecasts) are acting as if they were "over it", meaning that if you click on something, it will act as if you had clicked on the forecast rectangle in the background and not on the buttons from the filter tab.

I'm not sure if this is clear but it is extremely limiting in search parameters.

**Comment by SylvainChevalier** [comment] 2024-11-12 17:44
@exmateriae do you have any extensions and script blockers? What happens when you disable them?

**Comment by exmateriae** [comment] 2024-11-14 07:55
Sorry for the late reply. It is the same thing indeed! uBlock is the only thing that could have an impact that I can think of

**Comment by SylvainChevalier** [comment] 2024-11-14 15:18
Duplicate of #1338

**Closed by SylvainChevalier** 2024-11-14 15:18 UTC
Labels: Bug Report, Medium Priority
