### ISSUE TITLE
"Resolving soon" skips questions

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1257] opened 2024-11-04 18:55 UTC
## Current behavior
In AIB, this question is closed & unresolved and scheduled for Nov 1, 2024, but it does not appear in "Resolving soon".
![Screenshot 2024-11-04 at 1 55 10 PM](https://github.com/user-attachments/assets/8a84d1d3-74cd-4f11-982a-ae106f83b58e)

https://www.metaculus.com/questions/29010/

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by Tommetaculus** [comment] 2024-11-04 18:56
@SylvainChevalier @hickman-santini I'd like to request that this is high priority. I'm missing questions and spending considerable time trying to go back to figure out the resolutions.

**Comment by lsabor** [comment] 2024-11-06 16:50
I can't reproduce this. @Tommetaculus can you verify that it is still a problem?

**Comment by lsabor** [comment] 2024-11-06 17:39
discovered the issue - there was a filter that only responded with posts whose `scheduled_resolve_time` was in the future
replaced this with posts that have some `scheduled_resolve_time` and just aren't yet actually resolved.

I've applied another small fix that removes the application of the "open" filter when selecting "resolving soon".

Closing as complete

**Closed by lsabor** 2024-11-06 17:39 UTC
Labels: Bug Report, High Priority
