### ISSUE TITLE
Comments in comment tab of profile should say what question they pertain to

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#838] opened 2024-10-08 14:54 UTC
Instead of "Go to question" it should say the full question text.

![image](https://github.com/user-attachments/assets/840eab2f-c9d7-4eef-9816-7d09b4ad09e8)

**Comment by SylvainChevalier** [comment] 2024-10-08 15:53
thanks @ryooan!
duplicate of #740, closing.

**Closed** 2024-11-13 23:44 UTC
Labels: Feature Request, Medium Priority
