### ISSUE TITLE
Mobile prediction page labels are incorrect

### ISSUE THREAD

**Issue by hobson** [Metaculus/metaculus#960] opened 2024-10-11 01:07 UTC
## Current behavior
In Firefox on an Android phone, the date labels of the horizontal axis start at 2159 (2024 date is cut off at left edge of screen and unreadable) and the prediction statistics don't agree. Also times of day are displayed when only day or month resolution is appropriate for the question and the page does not have room for irrelevant time of day info.
![Screenshot_20241010-175642_Firefox Nightly](https://github.com/user-attachments/assets/f75ee26a-cbf0-482c-9b13-43942a7e0d2f)

## Expected/desired behavior
Previous released version of web page used  string length limits to truncate labels at a time resolution that was usable with interactive features such as the prediction slider. In the past it was possible to make predictions on date questions accurately. Now it is extremely difficult and the ux is misleading.
Date axis for the question in the screenshot aboutshould have year ticks only for perhaps 2024, 2026, 2028, 2030, 2032, 2034 or similar. 
Likewise the 25% median and 75% statistics should be YYYY-MM-DD format, without time of day.

**Comment by SylvainChevalier** [comment] 2024-10-11 11:57
Thank you for opening this @hobson.
The values look correct to me, though I agree that the formatting leaves something to be desired.
@lsabor related to #826

**Comment by SylvainChevalier** [comment] 2024-10-11 11:58
Duplicate of #826

**Closed by SylvainChevalier** 2024-10-11 11:58 UTC
