### ISSUE TITLE
too many sig figs on elections hub

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#821] opened 2024-10-07 19:03 UTC
https://www.metaculus.com/experiments/elections/

Displaying too many sig figs
![image](https://github.com/user-attachments/assets/42180511-e849-49e6-8875-fdae67e1f873)

**Comment by SylvainChevalier** [comment] 2024-10-11 10:37
Duplicate of #954

**Closed by SylvainChevalier** 2024-10-11 10:37 UTC
Labels: Simple, Bug Report, Medium Priority
