### ISSUE TITLE
Preserve tags and banner image when notebook text is edited

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1101] opened 2024-10-22 16:59 UTC
Editing a Notebook seems to remove the image and any news tags. This Notebook had the News Platform tag and this image until I edited it on platform just now: <https://www.metaculus.com/notebooks/29025/>

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1729616221571689?thread_ts=1729616221.571689&cid=C01Q9AQBVHB)

**Comment by ncarazon** [comment] 2024-11-01 17:21
I couldn't reproduce the issue with the image—it remains in the object (postData.notebook.image_url) after editing notebook. However, for some reason, the tags are deleted after making changes. I tried modifying the data we pass to the backend to ensure tags are saved, but this didn't make any difference. I believe this is a backend-related issue specifically in how we handle PUT requests for notebooks.
Here’s what the request body currently looks like:
```
"title": "title_string",
"notebook": {
  "markdown": "markdown_string"
}
```

Request body with categories:
```
"title": "title_string",
"notebook": {
  "markdown": "markdown_string"
},
"projects": {
  "categories": ["category-1", "category-2"...]
}
```

Both payloads result in empty categories after submission. @hlbmtc could you take a look?

**Comment by lsabor** [comment] 2024-11-06 21:52
Fixed the issue. When categories and tags weren't provided, they were assumed to be updated to be None, rather than just assuming no change to them.
This issue is fixed

Still, the notebook editing interface doesn't allow for adding / removing tags and will require more work to implement. Probably best to make another ticket as a feature request and most likely should be done by Hlib.

closing as complete - making another ticket

**Closed by lsabor** 2024-11-06 21:52 UTC
Labels: Bug Report, High Priority
