### ISSUE TITLE
Private projects need to be tagged as private

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#218] opened 2024-08-21 14:00 UTC
Currently someone with access to a private project can't see whether the project is public or private, needs a tag or label like it's currently shown on main, on both the project itself and on the tournaments / projects page.

Would also be handy to have the ability to edit a project from the front end like you currently can on main.

![image](https://github.com/user-attachments/assets/058ba571-7b7f-434f-a0cd-aaf9bc1c0f22)

![image](https://github.com/user-attachments/assets/4f0d4f6b-a9b0-477c-b365-d4af03e4724c)

![image](https://github.com/user-attachments/assets/16af1f47-700c-4114-8363-81cfeb8a8118)

**Comment by SylvainChevalier** [comment] 2024-09-03 14:45
Duplicate of #312

Re: editing on front-end, @ryooan what would you think of having a link to django admin (just for admins)? Maintaining a separate front-end edit page seems a bit wasteful to me.

**Comment by ryooan** [comment] 2024-09-03 14:51
@SylvainChevalier a link to admin just for admins would be fine, I think that would serve the purpose. Mainly would just like to avoid having to navigate and search for stuff in admin to the extent possible (if I were better at remembering urls it wouldn't be so much of a problem, but would be nice to not have to remember urls).

**Comment by SylvainChevalier** [comment] 2024-09-04 11:46
ok, covered in #398, closing this one.

**Closed by SylvainChevalier** 2024-09-04 11:46 UTC
Labels: Approved, Bug Report
