### ISSUE TITLE
Allow setting the CP reveal date as a % of the question's lifetime

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#295] opened 2024-08-29 11:07 UTC
Lifetime == from when it's opened to when it's expected to close.

**Comment by George3d6** [comment] 2024-08-29 11:07
Note: wait for #294 to be done before this one can be worked on

**Comment by SylvainChevalier** [comment] 2024-09-10 07:28
Duplicate of #123, closing.

**Closed by SylvainChevalier** 2024-09-10 07:28 UTC
Labels: Simple, Approved, Feature Request
